apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-every-twelve-hours
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: pgsql-backup
            image: aakarsh94/postgres-dump:v1
            env:
            - name: PGHOST
              value: "cronjobtest.postgres.database.azure.com"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "adventureworks"
            - name: PGUSER
              value: "Azureadmin@cronjobtest"
            - name: PGPASSWORD
              value: "P3CGULlUzA"
            - name: fileShareName
              value: "backup2"
            volumeMounts:
            - name: azurefileshare
              mountPath: /backup2
            securityContext:
              capabilities:
                add: ["SYS_ADMIN", "DAC_READ_SEARCH"]                   
          volumes:
          - name: azurefileshare
            azureFile:
              secretName: storage-secret
              shareName: backup2
              readOnly: false          
                     
