apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-backup
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: pgsql-backup
        image: aakarsh94/postgres-backup:v1
        env:
        - name: PGSOURCEHOST
          value: "cronjobtest.postgres.database.azure.com"
        - name: PGSOURCEPORT
          value: "5432"
        - name: PGSOURCEDATABASE
          value: "adventureworks"
        - name: PGSOURCEUSER
          value: "Azureadmin@cronjobtest"
        - name: PGSOURCEPASSWORD
          value: "P3CGULlUzA"
        - name: fileShareName
          value: "backup2"
        volumeMounts:
        - name: azurefileshare
          mountPath: /backup2
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "DAC_READ_SEARCH"]                   
      volumes:
      - name: azurefileshare
        azureFile:
          secretName: storage-secret
          shareName: backup2
          readOnly: false          
                     
